# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: THE GAME OF LIFE
run-name: Deploy to the game of life by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present

# Uploads the artefact in path     
    - uses: actions/upload-artifact@v3
      with:
          name: gameoflife-app
          path: ./dist
       
       
# Deploy on dev
  deployment:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
     
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Download artefact
          uses: actions/download-artifact@v2.1.1
          with:
            name: gameoflife-app
            path: ./dist
            
        - name: Copy files to the test website with the AWS CLI
          run:  |
            aws s3 sync ./dist/the-game-of-life/browser s3://thegameoflife-app-frontend
          